global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
      api_version: v2
scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    body_size_limit: "0"
    static_configs:
      - targets:
          - localhost:9090

  - job_name: fronted-scrap
    metrics_path: /api/metrics
    static_configs:
      - targets:
          - host.docker.internal:3000 # Frontend
